#!/bin/bash
#

REPLY=""

function get_project() {
	local _PDIR=$1
	if [ -e "$_PDIR/scripts/faddr2line" ]; then
		REPLY="kernel"
		return
	fi

	if [ -e "$_PDIR/buildlib/cbuild" ]; then
		REPLY="rdma-core"
		return
	fi

	if [ -e "$_PDIR/rdma/rdma.h" ]; then
		REPLY="iproute"
		return
	fi

	if [ -e "$_PDIR/x" ]; then
		REPLY="x-tools"
		return
	fi

	REPLY=""
}

function get_target() {
	local _PROJECT=$1
	local _TARGET=""
	if [ "$_PROJECT" == "rdma-core" ]; then
		_TARGET="rdma-core"
	fi

	if [ "$_PROJECT" == "kernel" ]; then
		_TARGET=$(git symbolic-ref --short HEAD)
		if [ "$_TARGET" != "rdma-next" ] && [ "$_TARGET" != "rdma-rc" ]; then
			TRACKED_BRANCH=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})
			if [ "$TRACKED_BRANCH" == "net-next/master" ]; then
				_TARGET="net-next"
			else
				if [ "$TRACKED_BRANCH" == "net/master" ]; then
					_TARGET="net-next"
				else
					# Let's put default for now
					_TARGET="rdma-next"
				fi
			fi
		fi
	fi

	if [ "$_PROJECT" == "iproute" ]; then
		_TARGET=$(git symbolic-ref --short HEAD)
		if [ "$_TARGET" != "iproute2-next" ] && [ "$_TARGET" != "iproute2-rc" ]; then
			# Let's put default for now
			_TARGET="iproute2-next"
		fi
	fi

	REPLY=$_TARGET
}
