#!/bin/bash
export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $DIR/common

PATCH=$(mktemp)
cat - > $PATCH

COUNT=$(grep PATCH $PATCH | grep Subject | grep -c rdma-core)
echo $COUNT
if [ $COUNT -eq 1 ]; then
	PRJ="rdma-core"
else
	COUNT=$(grep PATCH $PATCH | grep Subject | grep -c iproute)
	if [ $COUNT -eq 1 ]; then
		PRJ="iproute2"
	else
		PRJ="kernel"
	fi
fi

echo "Applying to $HOME/src/$PRJ"
cd $HOME/src/$PRJ

GERRIT=$(grep -c "Gerrit-Project:" $PATCH)
if [ $GERRIT -ge 1 ]; then
	ISSUE=$(grep "Gerrit-Change-Number:" $PATCH | head -1 | cut -d' ' -f2)
	GPROJECT=$(grep "Gerrit-Project:" $PATCH | head -1 | cut -d' ' -f2)
	PATCHSET=$(grep "Gerrit-PatchSet:" $PATCH | head -1 | cut -d' ' -f2)
	LINK="ssh://l-gerrit.mtl.labs.mlnx:29418/$GPROJECT refs/changes/${ISSUE: -2}/$ISSUE/$PATCHSET"
	git fetch $LINK && git cherry-pick FETCH_HEAD && git cl
else
	sed -i -e '/^Issue:[ 0-9]*/Id' -e '/^Change-id:[ 0-9]*/Id' $PATCH
	git am -s --reject $PATCH
fi

rm -f $PATCH
